version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - all-minilm
  - automd
  - bumpp
  - elevenlabs
  - fumadocs
  - gcornut
  - importantimport
  - koemotion
  - localai
  - Moeru
  - moeru-ai
  - mxbai-embed-large
  - nemo
  - nemotron
  - nomic-embed-text
  - Ollama
  - pkgroll
  - qwen
  - twoslash
  - typeschema
  - unspeech
  - valibot
  - Vitest
  - xsai
ignoreWords: []
import: []
