version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - all-minilm
  - automd
  - BAAI
  - bumpp
  - changelogithub
  - cognitivecomputations
  - deepseek
  - elevenlabs
  - eslintcache
  - fishaudio
  - fumadocs
  - Groq
  - importantimport
  - koemotion
  - masknet
  - mistralai
  - mixtral
  - moeru
  - moeru-ai
  - mxbai-embed-large
  - nemo
  - nemotron
  - netease
  - nomic
  - nomic-embed-text
  - Novita
  - ollama
  - openrouter
  - pkgroll
  - qwen
  - reranker
  - siliconflow
  - sonarjs
  - SoVITS
  - specdec
  - twoslash
  - typeschema
  - unspeech
  - valibot
  - vitest
  - wizardlm
  - xsai
  - xsfetch
  - xsschema
  - youdao
ignoreWords: []
import: []
