version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - all-minilm
  - automd
  - bumpp
  - changelogithub
  - elevenlabs
  - eslintcache
  - fumadocs
  - gcornut
  - importantimport
  - koemotion
  - masknet
  - moeru
  - moeru-ai
  - mxbai-embed-large
  - nemo
  - nemotron
  - nomic-embed-text
  - ollama
  - pkgroll
  - qwen
  - sonarjs
  - twoslash
  - typeschema
  - unspeech
  - valibot
  - vitest
  - xsai
ignoreWords: []
import: []
