version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - agentic
  - all-minilm
  - arktype
  - automd
  - BAAI
  - bumpp
  - Cerebras
  - changelogithub
  - codestral
  - cognitivecomputations
  - composio
  - deepinfra
  - deepseek
  - elevenlabs
  - eslintcache
  - fishaudio
  - fumadocs
  - ggml
  - Groq
  - Hunyuan
  - importantimport
  - koemotion
  - llms
  - masknet
  - mastra
  - ministral
  - minzipped
  - mistralai
  - mixtral
  - modelcontextprotocol
  - moeru
  - moeru-ai
  - mxbai-embed-large
  - nemo
  - nemotron
  - netease
  - nomic
  - nomic-embed-text
  - Novita
  - nums
  - ollama
  - openrouter
  - Plateforme
  - qwen
  - reranker
  - siliconflow
  - sonarjs
  - SoVITS
  - specdec
  - SSML
  - Stepfun
  - theguild
  - twoslash
  - typeschema
  - unspeech
  - valibot
  - vitest
  - wizardlm
  - xsai
  - xsfetch
  - xsschema
  - youdao
  - Zhipu
ignoreWords: []
import: []
